### PR TITLE
update pin

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by pelson** [comment]
@ocefpaf - wondering if you could point me to the issue tracking the status of conda-build 3? Would be nice to move that forwards to help with this kind of thing.

**Comment by ocefpaf** [comment]
> @ocefpaf - wondering if you could point me to the issue tracking the status of conda-build 3?

https://github.com/conda-forge/conda-forge.github.io/issues/460 and https://github.com/conda-forge/geos-feedstock/pull/25

> Would be nice to move that forwards to help with this kind of thing.

Indeed! We need our leader back to restart the meetings :wink:

**Comment by pelson** [comment]
Well there goes my afternoon with reading those! 😄 

> Indeed! We need our leader back to restart the meetings 😉

I'm interested in at the very least spinning up ad-hoc meetings to ensure there is sufficient comms between everybody. Watch this space...

**Comment by ocefpaf** [comment]
Travis-CI is passing on my instance. Merging this...

**Pull request merged**
